# Generated by Django 2.0.7 on 2020-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='empresa',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
    ]
