# Generated by Django 2.0.7 on 2020-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200218_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='empresa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
