# Generated by Django 2.0.7 on 2020-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200218_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
